### ISSUE TITLE
Hi~ 关于你申请了萌icp备案有一个问题

### ISSUE THREAD

**Issue by MisakaShell** [beiyaohhhc/Beiyao_Hexo#2]
您好，萌友
你申请的萌号现在有一个问题，你把萌icp备案的链接跳转到中国大陆的备案上去了，请您修正成您萌备的谢谢！
链接：https://icp.gov.moe/?keyword=20230063

**Comment by beiyaohhhc** [comment]
已修改 请审核

**Comment by MisakaShell** [comment]
已经被通过，谢谢！

**Comment by MisakaShell** [comment]
你好：www.beiyao.icu 您的个人主页申请的萌备无对接，请抓紧对接：https://icp.gov.moe/id.php?icp=20230526 ，如果对接完毕请回复此issues并且关闭，会给你加速通过。

**Comment by beiyaohhhc** [comment]
你好 由于最近个人原因 导致本备案无法申请 请取消 谢谢
